### ISSUE TITLE
Grades for surprise e-commerce page 1

### ISSUE THREAD

**Issue by AveryDion** [AveryDion/ecommerce-pattern-library#11]
My pattern library handled this surprise page well. The only problem is that the pattern for my links is white making them invisible on the page. For the final, I will change the default link pattern to a different colour and add a hover state. The table could also use some more styling to make it fit the branding of my website. Overall my pattern library did a good job with just a few minor changes that will need to be made.

@thomasjbradley

**Comment by thomasjbradley** [comment]
👍
