### ISSUE TITLE
Grades for Homepage Template

### ISSUE THREAD

**Issue by AveryDion** [AveryDion/ecommerce-pattern-library#2]
@thomasjbradley

<img width="692" alt="homepage-1" src="https://user-images.githubusercontent.com/43150615/77190070-f5dd5b80-6aae-11ea-8842-6a4953e6b0da.png">

<img width="692" alt="homepage-2" src="https://user-images.githubusercontent.com/43150615/77189900-aeef6600-6aae-11ea-983c-6e8a45c73a58.png">

**Comment by thomasjbradley** [comment]
It’d be nice if clicking on the featured products took you to actual product pages.
