### ISSUE TITLE
Featured Product Links Not Working

### ISSUE THREAD

**Issue by AveryDion** [AveryDion/ecommerce-pattern-library#4]
@thomasjbradley

I'm trying to link the featured cards on my index page to their product pages but it isn't working. I've tried a few different things but it seems that the variable for the link isn't being documented in the pattern on the pattern library. I'm not sure why.

**Comment by thomasjbradley** [comment]
Step 1:
https://github.com/AveryDion/ecommerce-pattern-library/blob/master/_patterns/cards/featured-card.html#L1
Add an include parameter into the `href` attribute: `href="{{include.url}}"`

Step 2:
Add a new attribute to the pattern code for that new parameter:
https://github.com/AveryDion/ecommerce-pattern-library/blob/master/index.html#L11

```liquid
{% pattern cards/featured-card url="/products/blah/" name="Ra…
```
