### ISSUE TITLE
Grades for Finalizing Pattern Docs

### ISSUE THREAD

**Issue by AveryDion** [AveryDion/ecommerce-pattern-library#5]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you committed & pushed this?

**Comment by AveryDion** [comment]
@thomasjbradley 

I don't have a commit specifically for this, but it was part of a different commit and has been pushed. It can be seen within the "Add links to the featured cards" commit.

In the future, I will make specific commits for the parts that need grades.

**Comment by thomasjbradley** [comment]
I think it just mustn’t have been pushed when I went to look at the `README.md`—all good now though.
