### ISSUE TITLE
Photo Array Not Working

### ISSUE THREAD

**Issue by AveryDion** [AveryDion/ecommerce-pattern-library#8]
@thomasjbradley

I'm trying to add my photo array to the product details pages and am having some issues. The example photos in the array won't change to the specific product images I put in the md file. I've included a screenshot of an error I received on the terminal, I tried to figure it out but couldn't find a solution. The JavaScript for the photo array also isn't working, I'm not sure why.

<img width="574" alt="Screen Shot 2020-04-02 at 3 11 35 PM" src="https://user-images.githubusercontent.com/43150615/78292423-0224d800-74f5-11ea-88b8-6fa83a49ae24.png">

**Comment by thomasjbradley** [comment]
Hmm. I’m wondering if you should use underscores for these variables: `product-image-1`?

**Comment by AveryDion** [comment]
I'm still getting the same error code in the terminal. It goes away if I put the name of the image instead of the variable. So I think the problem has to do with my variables inside the pattern?
`{% pattern cards/product-photo-array product_image_1="{{page.photo-array-1}}" product_image_2="{{page.photo-array-2}}" product_image_3="{{page.photo-array-3}}" %}
`

**Comment by thomasjbradley** [comment]
Um, right, okay. Try without the `"` and without the `{{`, like: 

```
product_image_1=page.photo-array-1
```

**Comment by AveryDion** [comment]
Okay, that fixed the error message and my images are showing up properly however the Javascript still isn't working.

**Comment by thomasjbradley** [comment]
We need to connect the JS in your `default.html`:
https://github.com/AveryDion/ecommerce-pattern-library/blob/master/_layouts/default.html#L15

```html
<script src="/js/main.js"></script>
```

**Comment by AveryDion** [comment]
Oh okay, I was wondering if I needed to link it somewhere. That fixed it. Thank you!
